#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom aniMotum fit_mpm
#' @importFrom aniMotum fit_ssm
#' @importFrom aniMotum grab
#' @importFrom aniMotum ssm_control
#' @importFrom data.table data.table
#' @importFrom data.table fread
#' @importFrom data.table frollapply
#' @importFrom data.table fwrite
#' @importFrom data.table rbindlist
#' @importFrom DBI dbConnect
#' @importFrom DBI dbDisconnect
#' @importFrom DBI dbListTables
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr group_split
#' @importFrom dplyr lag
#' @importFrom dplyr lead
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr right_join
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr semi_join
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom fs dir_create
#' @importFrom fs dir_ls
#' @importFrom fs file_delete
#' @importFrom fs file_exists
#' @importFrom future plan
#' @importFrom future.apply future_lapply
#' @importFrom httr authenticate
#' @importFrom httr GET
#' @importFrom httr timeout
#' @importFrom httr write_disk
#' @importFrom lubridate %within%
#' @importFrom lubridate ceiling_date
#' @importFrom lubridate ddays
#' @importFrom lubridate floor_date
#' @importFrom lubridate interval
#' @importFrom magrittr %>%
#' @importFrom nlme lme
#' @importFrom nlme lmeControl
#' @importFrom readr read_delim
#' @importFrom rlang .data
#' @importFrom RODBC odbcClose
#' @importFrom RODBC odbcDriverConnect
#' @importFrom RODBC sqlFetch
#' @importFrom rSRDL get.SRDLdb
#' @importFrom rSRDL qcDive
#' @importFrom sf sf_use_s2
#' @importFrom sf st_as_sf
#' @importFrom sf st_join
#' @importFrom sf st_read
#' @importFrom sf st_within
#' @importFrom sfheaders sf_to_df
#' @importFrom stats fitted
#' @importFrom stats median
#' @importFrom stats na.exclude
#' @importFrom stats na.omit
#' @importFrom stats predict
#' @importFrom stats quantile
#' @importFrom stats resid
#' @importFrom stats runif
#' @importFrom stats time
#' @importFrom stringr str_count
#' @importFrom stringr str_remove
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom tidyr drop_na
#' @importFrom tidyr separate_rows
#' @importFrom tidyselect everything
#' @importFrom tidyselect where
#' @importFrom utils unzip
## usethis namespace: end
NULL
